name: stepwars_app
description: StepWars MVP - A gamified fitness app where steps become weapons

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  google_fonts: ^6.2.1
  http: ^1.1.0 
  path_provider: ^2.0.11

  
  
  # State Management
  provider: ^6.1.5+1
  permission_handler: ^11.0.1
  pedometer: ^4.1.1
  health: ^13.2.0
  flutter_foreground_task: ^9.1.0

  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  games_services: ^4.1.1
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  clarity_flutter: ^1.4.3
  firebase_remote_config: ^5.5.0
  cached_network_image: ^3.3.1
  showcaseview: ^5.0.1
  upgrader: ^12.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: RobotoMono
  #     fonts:
  #       - asset: assets/fonts/RobotoMono-Regular.ttf

